### ISSUE TITLE
Create custome extension key value pair

### ISSUE THREAD

**Issue by anantbhula** [Osirium/format_cef#25]
Hi
First of all thank you so much for the library.  I am trying to use this wonderful library however running into blocker as some of our extensions are custom. Will you please guide me how I can create a custom extensions using this library. for eg. 'source_type' : 'hash' is not one of the predefined extensions

**Comment by graingert** [comment]
@anantbhula you can pass other fields and the values will be treated as strings. 

Generally you're not supposed to add your own extensions but use deviceCustomString(1-6) and labels eg:

```
{
    "deviceCustomString5": "hash",
    "deviceCustomString5Label: "sourceType",
}
```

**Comment by anantbhula** [comment]
appreciate your help thank you
